---
title: "COVID Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(plotly)
library(DT)
library(sf)
library(stringr)

load("counties_covid.rda")
counties_covid <- counties_covid %>%
  mutate(cases_pc = cases/(tpop/100000),
         deaths_pc = deaths/(tpop/100000))

#filter to just Ohio's counties
ohio <- counties_covid %>% 
  filter(state %in% c("Ohio")) %>% 
  mutate(tt = paste0(NAMELSAD, 
                    "\n", 
                    cases, 
                    " cases"))


library(crosstalk)
library(d3scatter)
library(leaflet)
ohio2 <- ohio %>%
  select(county, st, cases_pc, cases, repvote, geometry) %>%
  mutate(repvote = repvote*100,
         text = paste0(county, "\n", cases, " cases\n")) %>%
  select(-cases)
sny <- SharedData$new(ohio2)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# Plotly map of the log of cases
plot_ly(sny, split = ~ text,  color = ~cases_pc,  alpha = 1,
        hoverinfo="text", hoveron="fill",  showlegend=FALSE)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
# plot of cases by repvote
plot_ly(sny, x=~repvote, y=~cases_pc, text=~text,  width="100%") %>%
  add_markers(hoverinfo="text", hoveron="fill")


```

### Chart C

```{r}
# datatable using (DT) package
sny %>%
  datatable(extensions="Scroller",
  class="compact",
  colnames = c("County"="county",
               "State"="st",
               "# Cases/100k" = "cases_pc",
               "Republican Vote" = "repvote"),
  rownames=FALSE,
  options = list(paging=FALSE,
                 pageLength = 20,
                 scrollY = "350px",
                 columnDefs = list(list(className = 'dt-center',
                                        targets = 0:3),
                            list(visible=FALSE, targets=c(4,5))))) %>%
  formatRound(columns = c("Republican Vote", "# Cases/100k"), digits=0)
```









